import { createActionType } from '../../utils/reduxHelper';

export const CONTEXT = 'shop/address';

export const GET_PREDEFINE_LOCATION_LIST = `${CONTEXT}/GET_PREDEFINE_LOCATION_LIST`;
export const ADD_ADDRESS = `${CONTEXT}/ADD_ADDRESS`;
export const UPDATE_ADDRESS = `${CONTEXT}/UPDATE_ADDRESS`;
export const DELETE_ADDRESS = `${CONTEXT}/DELETE_ADDRESS`;
export const GET_MY_ADDRESSES = `${CONTEXT}/GET_MY_ADDRESSES`;
export const UPDATE_SELECTED_SHIPPING_ADDRESS = `${CONTEXT}/UPDATE_SELECTED_SHIPPING_ADDRESS`;
export const UPDATE_ERRORS = `${CONTEXT}/UPDATE_ERRORS`;

export const [
  GET_PREDEFINE_LOCATION_LIST_BEGIN,
  GET_PREDEFINE_LOCATION_LIST_SUCCESS,
  GET_PREDEFINE_LOCATION_LIST_FAIL,
  GET_PREDEFINE_LOCATION_LIST_END,
] = createActionType(
  GET_PREDEFINE_LOCATION_LIST,
);

export const [
  ADD_ADDRESS_BEGIN,
  ADD_ADDRESS_SUCCESS,
  ADD_ADDRESS_FAIL,
  ADD_ADDRESS_END,
] = createActionType(ADD_ADDRESS);

export const [
  UPDATE_ADDRESS_BEGIN,
  UPDATE_ADDRESS_SUCCESS,
  UPDATE_ADDRESS_FAIL,
  UPDATE_ADDRESS_END,
] = createActionType(UPDATE_ADDRESS);

export const [
  DELETE_ADDRESS_BEGIN,
  DELETE_ADDRESS_SUCCESS,
  DELETE_ADDRESS_FAIL,
  DELETE_ADDRESS_END,
] = createActionType(DELETE_ADDRESS);

export const [
  GET_MY_ADDRESSES_BEGIN,
  GET_MY_ADDRESSES_SUCCESS,
  GET_MY_ADDRESSES_FAIL,
  GET_MY_ADDRESSES_END,
] = createActionType(GET_MY_ADDRESSES);
