# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '9.0'
target 'iSalonBooking' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  # pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'FBSDKLoginKit', '5.6.0'
  pod 'FBSDKShareKit', '5.6.0'
  pod 'GoogleSignIn'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"

  # If you are using React Native <0.54, you will get the following error:
  # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
  # Use the following line instead:
  #pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS
  #pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
  #pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'


  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  # Pods for AppCenter
  pod 'appcenter', :path => '../node_modules/appcenter'
  pod 'appcenter-analytics', :path => '../node_modules/appcenter-analytics'
  pod 'appcenter-crashes', :path => '../node_modules/appcenter-crashes'

  pod 'AppCenter/Crashes', '~> 2.3.0'
  pod 'AppCenter/Analytics', '~> 2.3.0'
  pod 'AppCenterReactNativeShared', '~> 2.3.0'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  
  pod 'RNOpenAppSettings', :path => '../node_modules/react-native-app-settings'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-calendar-events', :path => '../node_modules/react-native-calendar-events'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end