import { createActionType } from '../../utils/reduxHelper';

export const CONTEXT = 'shop/productDetail';

export const GET_PRODUCT_DETAIL = `${CONTEXT}/GET_PRODUCT_DETAIL`;

export const [
  GET_PRODUCT_DETAIL_BEGIN,
  GET_PRODUCT_DETAIL_SUCCESS,
  GET_PRODUCT_DETAIL_FAIL,
  GET_PRODUCT_DETAIL_END,
] = createActionType(
  GET_PRODUCT_DETAIL,
);

export const GET_PRODUCT_VARIANTS = `${CONTEXT}/GET_PRODUCT_VARIANTS`;

export const [
  GET_PRODUCT_VARIANTS_BEGIN,
  GET_PRODUCT_VARIANTS_SUCCESS,
  GET_PRODUCT_VARIANTS_FAIL,
  GET_PRODUCT_VARIANTS_END,
] = createActionType(
  GET_PRODUCT_VARIANTS,
);

export const GET_PRODUCT_VARIANT_VALUES = `${CONTEXT}/GET_PRODUCT_VARIANT_VALUES`;

export const [
  GET_PRODUCT_VARIANT_VALUES_BEGIN,
  GET_PRODUCT_VARIANT_VALUES_SUCCESS,
  GET_PRODUCT_VARIANT_VALUES_FAIL,
  GET_PRODUCT_VARIANT_VALUES_END,
] = createActionType(
  GET_PRODUCT_VARIANT_VALUES,
);

export const UPDATE_SELECTED_PRODUCT_VARIANT = 'UPDATE_SELECTED_PRODUCT_VARIANT';
export const UPDATE_SELECTED_PRODUCT_QUANTITY = 'UPDATE_SELECTED_PRODUCT_QUANTITY';

export const GET_ALL_PRODUCT_VARIANTS = `${CONTEXT}/GET_ALL_PRODUCT_VARIANTS`;
export const [
  GET_ALL_PRODUCT_VARIANTS_BEGIN,
  GET_ALL_PRODUCT_VARIANTS_SUCCESS,
  GET_ALL_PRODUCT_VARIANTS_FAIL,
  GET_ALL_PRODUCT_VARIANTS_END
] = createActionType(GET_ALL_PRODUCT_VARIANTS);

export const UPDATE_REVIEWABLE = `${CONTEXT}/UPDATE_REVIEWABLE`;

export const UPDATE_PRODUCT_FAVORITE = `${CONTEXT}/UPDATE_PRODUCT_FAVORITE`;
export const [
  UPDATE_PRODUCT_FAVORITE_BEGIN,
  UPDATE_PRODUCT_FAVORITE_SUCCESS,
  UPDATE_PRODUCT_FAVORITE_FAIL,
  UPDATE_PRODUCT_FAVORITE_END,
] = createActionType(
  UPDATE_PRODUCT_FAVORITE
);

export const CLEAR_PRODUCT_INFO = `${CONTEXT}/CLEAR_PRODUCT_INFO`;
export const [
  CLEAR_PRODUCT_INFO_BEGIN,
  CLEAR_PRODUCT_INFO_SUCCESS,
  CLEAR_PRODUCT_INFO_FAIL,
  CLEAR_PRODUCT_INFO_END
] = createActionType(CLEAR_PRODUCT_INFO);

export const FETCH_FAVORITED_PRODUCTS = `${CONTEXT}/FETCH_FAVORITED_PRODUCTS`;
export const [
  FETCH_FAVORITED_PRODUCTS_BEGIN,
  FETCH_FAVORITED_PRODUCTS_SUCCESS,
  FETCH_FAVORITED_PRODUCTS_FAIL,
  FETCH_FAVORITED_PRODUCTS_END
] = createActionType(FETCH_FAVORITED_PRODUCTS);
