import { createActionType } from '../../utils/reduxHelper';

export const CONTEXT = 'shop/home';

export const GET_SPOTLIGHT_ITEMS = `${CONTEXT}/GET_SPOTLIGHT_ITEMS`;
export const GET_ALL_PRODUCTS = `${CONTEXT}/GET_ALL_PRODUCTS`;
export const GET_PRODUCTS_FOR_CATEGORY = `${CONTEXT}/GET_PRODUCTS_FOR_CATEGORY`;
export const GET_CURRENT_FLASH_SALE = `${CONTEXT}/GET_CURRENT_FLASH_SALE`;
export const GET_FLASH_SALE_PRODUCTS = `${CONTEXT}/GET_FLASH_SALE_PRODUCTS`;

export const [
  GET_SPOTLIGHT_ITEMS_BEGIN,
  GET_SPOTLIGHT_ITEMS_SUCCESS,
  GET_SPOTLIGHT_ITEMS_FAIL,
  GET_SPOTLIGHT_ITEMS_END
] = createActionType(GET_SPOTLIGHT_ITEMS);

export const [
  GET_ALL_PRODUCTS_BEGIN,
  GET_ALL_PRODUCTS_SUCCESS,
  GET_ALL_PRODUCTS_FAIL,
  GET_ALL_PRODUCTS_END
] = createActionType(GET_ALL_PRODUCTS);

export const [
  GET_PRODUCTS_FOR_CATEGORY_BEGIN,
  GET_PRODUCTS_FOR_CATEGORY_SUCCESS,
  GET_PRODUCTS_FOR_CATEGORY_FAIL,
  GET_PRODUCTS_FOR_CATEGORY_END
] = createActionType(GET_PRODUCTS_FOR_CATEGORY);

export const [
  GET_CURRENT_FLASH_SALE_BEGIN,
  GET_CURRENT_FLASH_SALE_SUCCESS,
  GET_CURRENT_FLASH_SALE_FAIL,
  GET_CURRENT_FLASH_SALE_END
] = createActionType(GET_CURRENT_FLASH_SALE);

export const [
  GET_FLASH_SALE_PRODUCTS_BEGIN,
  GET_FLASH_SALE_PRODUCTS_SUCCESS,
  GET_FLASH_SALE_PRODUCTS_FAIL,
  GET_FLASH_SALE_PRODUCTS_END,
] = createActionType(GET_FLASH_SALE_PRODUCTS);
